/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120957-g66e40840d1-20250903"
#endif /* AVUTIL_FFVERSION_H */
